//
// Owner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Owner: Codable {

    public var id: Int?
    public var login: String?
    public var avatarUrl: String?
    public var url: String?

    public init(id: Int?, login: String?, avatarUrl: String?, url: String?) {
        self.id = id
        self.login = login
        self.avatarUrl = avatarUrl
        self.url = url
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case login
        case avatarUrl = "avatar_url"
        case url
    }


}

