//
// RepositoriesList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct RepositoriesList: Codable {

    public var status: String?
    public var totalCount: Int?
    public var items: [Repository]?

    public init(status: String?, totalCount: Int?, items: [Repository]?) {
        self.status = status
        self.totalCount = totalCount
        self.items = items
    }

    public enum CodingKeys: String, CodingKey { 
        case status
        case totalCount = "total_count"
        case items
    }


}

