//
// Repository.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Repository: Codable {

    public var id: Int?
    public var name: String?
    public var description: String?
    public var fullName: String?
    public var url: String?
    public var owner: Owner?

    public init(id: Int?, name: String?, description: String?, fullName: String?, url: String?, owner: Owner?) {
        self.id = id
        self.name = name
        self.description = description
        self.fullName = fullName
        self.url = url
        self.owner = owner
    }

    public enum CodingKeys: String, CodingKey { 
        case id
        case name
        case description
        case fullName = "full_name"
        case url
        case owner
    }


}

